### ISSUE TITLE
Controller HA failed to allocate EIP

### ISSUE THREAD

**Issue by satya5186** [AviatrixSystems/Controller-HA-for-AWS#75]
ERROR Customer received: 

- Instance launched from Autoscaling
- Failed in assigning EIP An error occurred (Resource.AlreadyAssociated) when calling the AssociateAddress operation: resource eipalloc-dba68de5 is already associated with associate-id eipassoc-031c956d49864aba9
- Operation failed due to: Could not assign EIP

Need to implement retry for all API calls

**Comment by arvindsree** [comment]
Hello,
Did this happen when the EIP was assigned to a different instance ?

**Comment by arvindsree** [comment]
Closing for now.  Does not seem to be a valid scenario. Please re-open if you have more information
